# -*- coding: utf-8 -*-
"""mean_var_std.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18JDeU4nUFgbVmv2lkaD8Zm8nv-BPazij
"""

import numpy as np

def calculate(list):
    # Check if the input list has exactly 9 elements
    if len(list) != 9:
        raise ValueError("List must contain nine numbers.")

    # Convert the list into a 3x3 NumPy array
    matrix = np.array(list).reshape(3, 3)

    # Calculate the metrics
    mean_axis1 = np.mean(matrix, axis=0).tolist()
    mean_axis2 = np.mean(matrix, axis=1).tolist()
    mean_flattened = np.mean(matrix).tolist()

    variance_axis1 = np.var(matrix, axis=0).tolist()
    variance_axis2 = np.var(matrix, axis=1).tolist()
    variance_flattened = np.var(matrix).tolist()

    std_dev_axis1 = np.std(matrix, axis=0).tolist()
    std_dev_axis2 = np.std(matrix, axis=1).tolist()
    std_dev_flattened = np.std(matrix).tolist()

    max_axis1 = np.max(matrix, axis=0).tolist()
    max_axis2 = np.max(matrix, axis=1).tolist()
    max_flattened = np.max(matrix).tolist()

    min_axis1 = np.min(matrix, axis=0).tolist()
    min_axis2 = np.min(matrix, axis=1).tolist()
    min_flattened = np.min(matrix).tolist()

    sum_axis1 = np.sum(matrix, axis=0).tolist()
    sum_axis2 = np.sum(matrix, axis=1).tolist()
    sum_flattened = np.sum(matrix).tolist()

    # Create and return the dictionary with the results
    calculations = {
        'mean': [mean_axis1, mean_axis2, mean_flattened],
        'variance': [variance_axis1, variance_axis2, variance_flattened],
        'standard deviation': [std_dev_axis1, std_dev_axis2, std_dev_flattened],
        'max': [max_axis1, max_axis2, max_flattened],
        'min': [min_axis1, min_axis2, min_flattened],
        'sum': [sum_axis1, sum_axis2, sum_flattened]
    }

    return calculations

calculate([0,1,2,3,4,5,6,7,8])

