# -*- coding: utf-8 -*-
"""sea_level_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1na3NierU_KnCycahFf_DzVJIT60A_98n
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

# 1. Import the data
def import_data():
    df = pd.read_csv('epa-sea-level.csv')
    return df

# 2. Create the scatter plot and fit the regression lines
def draw_plot():
    # Import the data
    df = import_data()

    # Create scatter plot
    plt.figure(figsize=(10, 6))
    plt.scatter(df['Year'], df['CSIRO Adjusted Sea Level'], color='blue', label='Data')

    # Create first line of best fit (using all data)
    slope, intercept, r_value, p_value, std_err = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])
    years_extended = pd.Series(range(1880, 2051))
    sea_level_pred = intercept + slope * years_extended
    plt.plot(years_extended, sea_level_pred, 'r', label='Best Fit Line 1880-2050')

    # Create second line of best fit (using data from 2000 onwards)
    df_recent = df[df['Year'] >= 2000]
    slope_recent, intercept_recent, r_value_recent, p_value_recent, std_err_recent = linregress(df_recent['Year'], df_recent['CSIRO Adjusted Sea Level'])
    sea_level_pred_recent = intercept_recent + slope_recent * years_extended
    plt.plot(years_extended, sea_level_pred_recent, 'green', label='Best Fit Line 2000-2050')

    # Add labels and title
    plt.xlabel('Year')
    plt.ylabel('Sea Level (inches)')
    plt.title('Rise in Sea Level')

    # Add legend
    plt.legend()

    # Save plot and return data for testing (if needed)
    plt.savefig('sea_level_plot.png')
    return plt.gca()

# 3. Generate and display the plot
if __name__ == "__main__":
    ax = draw_plot()
    plt.show()