# -*- coding: utf-8 -*-
"""time_series_visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ONSfYPIJtcZqHQ599FaLNnQtB6TTq9D
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Import the data and clean it
def import_and_clean_data():
    df = pd.read_csv('fcc-forum-pageviews.csv', parse_dates=['date'], index_col='date')

    # Filter out the top 2.5% and bottom 2.5% of the data
    df = df[(df['value'] >= df['value'].quantile(0.025)) & (df['value'] <= df['value'].quantile(0.975))]

    return df

# 2. Create the line plot
def draw_line_plot():
    df = import_and_clean_data()

    # Draw the line plot
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(df.index, df['value'], color='tab:red')
    ax.set_title('Daily freeCodeCamp Forum Page Views 5/2016-12/2019')
    ax.set_xlabel('Date')
    ax.set_ylabel('Page Views')

    # Save the plot
    fig.savefig('line_plot.png')
    return fig

# 3. Create the bar plot
def draw_bar_plot():
    df = import_and_clean_data()

    # Create a new DataFrame for the bar plot
    df_bar = df.copy()
    df_bar['year'] = df_bar.index.year
    df_bar['month'] = df_bar.index.month_name()

    # Pivot table to get the average page views per month for each year
    df_bar = df_bar.groupby(['year', 'month'])['value'].mean().unstack()

    # Draw the bar plot
    fig = df_bar.plot(kind='bar', figsize=(12, 8)).figure
    plt.xlabel('Years')
    plt.ylabel('Average Page Views')
    plt.legend(title='Months')
    plt.xticks(rotation=45)

    # Save the plot
    fig.savefig('bar_plot.png')
    return fig

# 4. Create the box plots
def draw_box_plot():
    df = import_and_clean_data()

    # Prepare data for box plots
    df_box = df.copy()
    df_box['year'] = df_box.index.year
    df_box['month'] = df_box.index.strftime('%b')
    df_box['month_num'] = df_box.index.month
    df_box = df_box.sort_values('month_num')

    # Draw the box plots using Seaborn
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

    sns.boxplot(x='year', y='value', data=df_box, ax=ax1)
    ax1.set_title('Year-wise Box Plot (Trend)')
    ax1.set_xlabel('Year')
    ax1.set_ylabel('Page Views')

    sns.boxplot(x='month', y='value', data=df_box, ax=ax2, order=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
    ax2.set_title('Month-wise Box Plot (Seasonality)')
    ax2.set_xlabel('Month')
    ax2.set_ylabel('Page Views')

    # Save the plot
    fig.savefig('box_plot.png')
    return fig

# 5. Generate and display all visualizations
if __name__ == "__main__":
    # Draw and show the line plot
    line_plot_fig = draw_line_plot()
    plt.show(line_plot_fig)

    # Draw and show the bar plot
    bar_plot_fig = draw_bar_plot()
    plt.show(bar_plot_fig)

    # Draw and show the box plot
    box_plot_fig = draw_box_plot()
    plt.show(box_plot_fig)